/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mkalashnikov.bingogame.UI;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Point;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import mkalashnikov.bingogame.BingoGame;
import mkalashnikov.bingogame.BingoPoint;
import mkalashnikov.bingogame.CellState;
import mkalashnikov.bingogame.ImagePanel;

/**
 * Юзер интерфейс Бинго!
 *
 * @author Макс
 */
public class BingoUI extends javax.swing.JFrame {

    private int fieldSize;

    private int level;

    private BingoGame game;

    private int step;

    private int stepsToUpDifficulty;

    private Point previousPoint;

    /**
     * Creates new form BingoUI
     */
    public BingoUI() {
        initComponents();
        btnHelp.setToolTipText("<html>Клик по клетке отмечает эту клетку, а так же соседние по вертикали и горизонтали<br>Если клетка уже отмечена, то отметка снимается<br>На каждый нулевой шаг нужно создать одну линию из отмеченных клеток</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGameField = new javax.swing.JPanel();
        lblThumbnail = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        lblSizeTitle = new javax.swing.JLabel();
        lblStepsToBingoTitle = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblStepsToBingo = new javax.swing.JLabel();
        lblScoreTitle = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bingo!");
        setResizable(false);

        panelGameField.setBackground(new java.awt.Color(153, 153, 255));
        panelGameField.setPreferredSize(new java.awt.Dimension(600, 600));

        lblThumbnail.setFont(new java.awt.Font("Segoe UI Emoji", 0, 48)); // NOI18N
        lblThumbnail.setText("BINGO!");

        javax.swing.GroupLayout panelGameFieldLayout = new javax.swing.GroupLayout(panelGameField);
        panelGameField.setLayout(panelGameFieldLayout);
        panelGameFieldLayout.setHorizontalGroup(
            panelGameFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGameFieldLayout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(lblThumbnail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        panelGameFieldLayout.setVerticalGroup(
            panelGameFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGameFieldLayout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(lblThumbnail, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
        );

        btnStart.setText("Начать");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblSizeTitle.setText("Размер:");

        lblStepsToBingoTitle.setText("Шагов до бинго:");

        lblSize.setText("0");

        lblStepsToBingo.setText("0");

        lblScoreTitle.setText("Счет:");

        lblScore.setText("0");

        btnHelp.setText("?");
        btnHelp.setToolTipText("Test");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(btnHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(lblSizeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSize)
                        .addGap(35, 35, 35)
                        .addComponent(lblScoreTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblScore)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStepsToBingoTitle)
                        .addGap(18, 18, 18)
                        .addComponent(lblStepsToBingo))
                    .addComponent(panelGameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(lblSizeTitle)
                    .addComponent(lblStepsToBingoTitle)
                    .addComponent(lblSize)
                    .addComponent(lblStepsToBingo)
                    .addComponent(lblScoreTitle)
                    .addComponent(lblScore)
                    .addComponent(btnHelp))
                .addGap(18, 18, 18)
                .addComponent(panelGameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Начать игру
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if (game == null || !game.getIsRunning()) {
            lblThumbnail.setVisible(false);
            level = 1;
            fieldSize = 4 + level;
            step = level + 1;
            stepsToUpDifficulty = level + 1;
            createButtons();
            panelGameField.setLayout(new GridLayout(fieldSize, fieldSize));

            game = new BingoGame();
            var modCells = game.start(1, true);
            renderCells(modCells);
            updateLabels();
        }
    }//GEN-LAST:event_btnStartActionPerformed

    // Обработчик кнопки "?"
    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        JOptionPane.showMessageDialog(this, "<html>Клик по клетке отмечает эту клетку, а так же соседние по вертикали и горизонтали<br>Если клетка уже отмечена, то отметка снимается<br>На каждый нулевой шаг нужно создать одну линию из отмеченных клеток<br><br>Автор: Калашников Максим</html>");
    }//GEN-LAST:event_btnHelpActionPerformed

    // Увеличить сложность
    private void increaseDifficulty() {
        level++;
        fieldSize = 4 + level;
        step = level + 1;
        stepsToUpDifficulty = level + 1;
        createButtons();
        panelGameField.setLayout(new GridLayout(fieldSize, fieldSize));
        var modCells = game.start(level, false);
        renderCells(modCells);
        updateLabels();
    }

    // Обработчик нажатия на любую ячейку.
    private void bingoButtonActionPerformed(BingoButton btn) {
        if (!game.getIsRunning() || (previousPoint != null && (btn.rowIndex == previousPoint.x && btn.colIndex == previousPoint.y))) {
            return;
        }

        var modCells = game.markCell(new Point(btn.rowIndex, btn.colIndex), step == 0);
        var failReason = game.GetFailReason();
        if (!failReason.isEmpty()) {
            renderCells(game.GetFullField());
            JOptionPane.showMessageDialog(this, String.format("%s Ваш счет: %d", failReason, game.getScore()));
            panelGameField.setEnabled(false);
            game.stop();
            return;
        }

        renderCells(modCells);
        if (step > 0) {
            step--;
        } else {
            step = level + 1;
            stepsToUpDifficulty--;
            if (stepsToUpDifficulty <= 0) {
                JOptionPane.showMessageDialog(this, "Уровень пройден! Сложность увеличена!");
                increaseDifficulty();
                return;
            }
        }

        updateLabels();
        previousPoint = new Point(btn.rowIndex, btn.colIndex);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BingoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BingoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BingoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BingoUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BingoUI().setVisible(true);
            }
        });
    }

    // Отрисовать кнопки-клетки
    private void renderCells(List<BingoPoint> modifiedCells) {
        var components = panelGameField.getComponents();
        for (var modCell : modifiedCells) {
            var cell = Arrays.stream(components)
                    .filter(p -> p instanceof BingoButton)
                    .map(bb -> (BingoButton) bb)
                    .filter(b -> b.rowIndex == modCell.x && b.colIndex == modCell.y)
                    .findFirst().get();
            if (modCell.cellState == CellState.Clean) {
                cell.setBackground(Color.WHITE);
            } else if (modCell.cellState == CellState.Marked) {
                cell.setBackground(Color.BLUE);
            } else if (modCell.cellState == CellState.Bingoed) {
                cell.setBackground(Color.GREEN);
            } else {
                cell.setBackground(Color.RED);
            }
        }

        panelGameField.revalidate();
    }

    // Обновить значения лейблов.
    private void updateLabels() {
        lblSize.setText(String.format("%sx%s", fieldSize, fieldSize));
        lblStepsToBingo.setText(String.valueOf(step));
        lblScore.setText(String.valueOf(game.getScore()));
    }

    // Заполнить панель кнопками-клетками.
    private void createButtons() {
        panelGameField.removeAll();
        for (int i = 0; i < fieldSize; i++) {
            for (int j = 0; j < fieldSize; j++) {
                var btn = new BingoButton(j, i);
                btn.setBackground(Color.WHITE);
                btn.addActionListener(l -> {
                    bingoButtonActionPerformed(btn);
                });
                panelGameField.add(btn);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreTitle;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSizeTitle;
    private javax.swing.JLabel lblStepsToBingo;
    private javax.swing.JLabel lblStepsToBingoTitle;
    private javax.swing.JLabel lblThumbnail;
    private javax.swing.JPanel panelGameField;
    // End of variables declaration//GEN-END:variables
}
